[package]
name = "chat-server"
version = "0.1.0"
edition = "2021"

[features]
default = []
http = ["axum", "tower-http"]

[dependencies]
chat-common = { workspace = true }

quic-session = { workspace = true }
framework = { workspace = true }

anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
env_logger = { workspace = true }
log = { workspace = true }
#static-web-server = { version = "2.33.1", features = ["directory-listing"], optional = true }

tower-http = { workspace = true, features = ["fs"], optional = true }
axum = { workspace = true, optional = true }
