[package]
name = "framework"
version = "0.1.0"
edition = "2021"

[dependencies]
web-transport = { workspace = true }
serde = { workspace = true, features = ["derive"] }
#tarpc = { git = "https://github.com/Masterchef365/tarpc.git", branch = "resolver-trouble", default-features = false }
tarpc = { workspace = true, features = ["serde1"] }
#tarpc = { version = "0.34.0", features = ["serde1"], default-features = false }
futures = { workspace = true }
bincode = { workspace = true, features = ["serde"] }
bytes = { workspace = true }
async-stream = { workspace = true }
thiserror = { workspace = true }

tokio-util = { workspace = true }
tokio = { workspace = true, features = ["io-util"] }
anyhow = { workspace = true }
serde_json = { workspace = true }

#polyfill-tokio-mem = { path = "../../polyfill-tokio-mem" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.46", features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

